services:
  api:
    build:
      context: .
      target: production
    image: cyna-backend:latest
    env_file:
      - .env
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://root:${DATABASE_PASSWORD}@mongo:27017/cyna?authSource=admin
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:3000}
    ports:
      - '${API_PORT:-3000}:3000'
    volumes:
      - storage_data:/app/storage
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  storage_data:
    driver: local
